apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.Kubernetes.io/revision: "2"
  generation: 4
  labels:
    run: tbncollect
  name: tbncollect
  namespace: default
  resourceVersion: "427"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tbncollect
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: tbncollect
    spec:
      containers:
      - image: turbinelabs/tbncollect:latest
        imagePullPolicy: IfNotPresent
        name: tbncollect
        env:
        - name: TBNCOLLECT_CMD
          value: kubernetes
        - name: TBNCOLLECT_API_ZONE_NAME
          value: testbed
        - name: TBNCOLLECT_API_KEY
          valueFrom:
            secretKeyRef:
              name: tbnsecret
              key: apikey
        resources: {}
